travis:
  secure:
    BINSTAR_TOKEN: NHRBHqmkD+vQPpTXeIeUGnbw3smMxnwo/kHL5AoNK4ybqMI839JZbJ0vBPUfzCilwtbYB0UAHJdAjldozSAMb49tGsvLP3AjJrBWHLEjhQj48lPLgNlu4bbfqg5p448n3+0gQ+t/LapTdKrYcSxzhAm90XskqqbSXSn9pXvCO3Htlcyv8NmXsLzyo43QYtUQBwT4XwiSbo1Vx7/D4VFYxPAO0WjjbkRYACDVDm1H0D4FpNkw5Z3e+33QGmzIrIi59DN4Stu0y2OXcNylqIOPBzW18VyyZAkzbRWoruZ4KlHVf1YcLEWkIg2fi2um0XhaMe+mwZLzXnzTE7H1Jri9C9AUV2+/75XIJx/g+sDPv+dwMHBvpMD2cZln2prw+ggIhibkCzwq60iNoYga0wa1wJPNNsLVMrfP060NB4h1r4AEZ45PULwe6i7bxlrQrAJ194C7+MN2+vmtoOoU1ia0PfmHXSd4iONLm//hrBTVMu3QOUc1INs/FDabNvoIlf5keKDLYsE/pFrtg+a7YpxyNzOy1AJ5twCl0fBS4xdUp/mrKMw8/k/Ofg8yDEIkQFe/+wc6vUSl3pcIkW3NMfc90ckABIrbMWOvEZrBzxI/m+3FXEM67g4p40gZ9Jqv1beAgcPtUnbgZ8Ap6kHIg7852RBboq3Yi5GXln2ml0rxzg4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
