travis:
  secure:
    BINSTAR_TOKEN: TdzMUYVwy6p8gyBLyZfGUImyb8V9HGBxAjIoEQXtVnMcpfBBbmx46sJSf+Vs/AwvmJhtpyjJYfNPRGrc/3nQc0h2/fEecb4e1KXb1421u891YM0hNQE56jcM7PUHB/meKPoOxFt6vSiuZ9gz3e+gyOLzPETdgy8zpg3N5jnanFIEcmf0VsGS0QdbcLWoKEpIN5L5wtIPe2hfugkitoaLW8/GTiXED5P4ngmNUn8wPHskcDkz5OuqTsr8uo2U5WogHaFq+7e/irMEIS0Nv6sqfojphMpy5426tWNfblOqHJStEjQlTdJCt5hgrGDGPjlQLLjwP4RD5HzO9rAzVKpj9VkOGfFncBtG2wuvcW1QhePMxyAcAF7pFC1+DLwg1JC/yIboUm6EAmRxZHYOjXXp/ih6U/CFyKON20GxXB/znv3t14mfIl8qXwya5fYGNlM+AvevjmLgJ07wL2uG7o/FvuZQXxqXiTIkqra3HsP9UVomuZKoily+4tlsXiq1LdItO3QZG5lRNCGnMB+HjpHPDDXPa/sEqpVIg6l6y/shQilP3zsKDJoPjH62Pwcq1u6SqhBzLbf9yMZ30UFBOlB/gY5SjGP6lVtJehhsc3kxJ5oVgeRLIYAfOthqS1KXksXQMVZad/gDY+xZLeRBpucIbfjIjhWdh271rjq4oFksxj0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
